### ISSUE TITLE
Stable API, semantic versioning and road to 1.0

### ISSUE THREAD

**Issue by dtantsur** [pyudev/pyudev#131]
This is a catch-all bug to track our recent discussion on subj. It would be awesome if pyudev would settle on some API its maintainers are ready to support long-term. http://semver.org/ could be used from that point to communicate the impact of the release in its version.

**Comment by dtantsur** [comment]
All openstack clients are examples of using semver, by the way. For example, many of them have bumped their major version when dropping support for Python 2.6, as it was considered a breaking change. Another example was oslo set of libraries (openstack common libraries) switching from oslo.xxx python namespace to oslo_xxx. In both cases some reasonable deprecation period was observed.

**Comment by mulkieran** [comment]
The original developer, @lunaryorn, put together a very extensive test suite which embodied a lot of the invariants he expected to hold for his implementation. One of the things that I can do is run these tests on realistic, large, storage configurations. In doing so, I've run across a bunch of surprises which have been due to a variety of things. Some of them have been systemd bugs, for some of them it is still unknown what is really responsible, some of them have been incorrect assumptions about libudev embedded in the design of the pyudev API itself. I can't guarantee that I will not encounter further surprises, and so, it seems precipitate to settle on the current API as the one to stick with.

I welcome contributions to Step (1) of this recommended semantic versioning process;
Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive.
Since the current API may be rather flawed, it should probably be specified in a document, rather than in the code itself.

**Comment by mulkieran** [comment]
Perhaps this tempest in a teacup has blown itself out.
