### ISSUE TITLE
Exception AttributeError: "'Context' object has no attribute '_libudev'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x6b922870>> ignored

### ISSUE THREAD

**Issue by rag2180** [pyudev/pyudev#421]
I am getting the following exception in my code randomly. This error was captured using sentry. 

`Exception AttributeError: "'Context' object has no attribute '_libudev'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x6b922870>> ignored`

Following is my code:

```
    import pyudev
    def find_hard_port(vendor_id, product_id):
        """
        This is used to find port number from among 1.1, 1.2, 1.3, 1.4
        :return:
        """
        _p = None
        context = pyudev.Context()
        for device in context.list_devices(subsystem='tty', ID_BUS='usb'):
            if vendor_id == device['ID_VENDOR_ID'] and product_id == device['ID_MODEL_ID']:
                _p = re.findall(r'1\.[1-9]', device['DEVPATH'])[-1]

        return _p
```

**Comment by mulkieran** [comment]
I can't really diagnose from here. Once the context is created, it _must_ have a ```_libudev``` attribute. And the ```__del__``` method _should_ only be called by the garbage collector. And there is no code that I can find that explicitly remove the ```_libudev``` attribute. Right now, the behavior is not inconsistent with the garbage collector trying to collect the Context object twice, somehow.

**Comment by parthgoel06** [comment]
I also faced this issue which @rag2180 mentioned and I found this.

**Source -** [](https://www.studytonight.com/python/destructors-in-python)

_**Description-**_
In object-oriented programming, a destructor is only called in case an object is successfully created, because if any exception occurs in the constructor then the constructor itself destroys the object.
But in python, if any exception occurs in the __init__ method while initializing the object, in that case too, the method __del__ gets called.
Hence, even though the object was never initialized correctly, the __del__ method will try to empty all the resources and variables and in turn, may lead to another exception.

_**Example code to reproduce the error-**_
```
class Example():
	def __init__(self, x):
	    # for x = 0, raise exception
		if x == 0:
			raise Exception();
		self.x = x;
		
	def __del__(self):
		print (self.x)

# creating an object
myObj = Example();
# to delete the object explicitly
del myObj
```

_**Error-**_
```
Exception exceptions.AttributeError: "'Example' object has no attribute 'x'" in <bound
 method Example.__del__ of <__main__.Example object at 0x02449570>> ignored
```

_**Context class of pyudev.core-**_
```
class Context(object):
    def __init__(self):
        """
        Create a new context.
        """
        self._libudev = load_ctypes_library('udev', SIGNATURES, ERROR_CHECKERS)
        self._as_parameter_ = self._libudev.udev_new()

    def __del__(self):
        self._libudev.udev_unref(self)
```
We can modify this class as per the solution given below.

_**Solution I found on StackOverflow-**_
**Source -** [](https://stackoverflow.com/questions/18058730/python-attributeerror-on-del)
**Solution -**  
__del__ method assumes that the class is still present by the time it is called.
This assumption is incorrect. The class has already been cleared when your Python program exits and is now set to None.

**Test if the global reference to the class still exists first:**
Solution code for the problem mentioned on the above mentioned StackOverflow link-
```
def __del__(self):
    if Groupclass:                          # checking if the global reference to the class still exists or not
        Groupclass.count -= 1
```

or use type() to get the local reference:
```
def __del__(self):
    type(self).count -= 1
```

I also found this - [](https://stackoverflow.com/questions/35327164/python-destructor-for-failed-constructor)

These are my findings for the mentioned issue. I haven't tested this solution thoroughly so there can be something that I'm missing here. Please verify if this is a viable solution or not.

**Comment by parthgoel06** [comment]
**Also in one of the above StackOverflow link, I found a warning from the __del__ hook documentation if it helps-** 

> Warning: Due to the precarious circumstances under which __del__() methods are invoked, exceptions that occur during their execution are ignored, and a warning is printed to sys.stderr instead. Also, when __del__() is invoked in response to a module being deleted (e.g., when execution of the program is done), other globals referenced by the __del__() method may already have been deleted or in the process of being torn down (e.g. the import machinery shutting down). For this reason, __del__() methods should do the absolute minimum needed to maintain external invariants. Starting with version 1.5, Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the __del__() method is called.

**Comment by mulkieran** [comment]
Ok. This looks like a reasonable explanation for why the exception is occurring. I think ```hasattr``` is the best choice and raising an exception indicating the real problem, in the case the attribute has not been set.
